apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - | 
              curl -H "Content-Type: application/json" -H "X-ClientCode: shashi_train" --request POST --data '{"Sponsor":{"SponsorId":"boeing"}}' http://bbcn-api-integrations/service/1.0/sponsorlookup 
          restartPolicy: OnFailure
