apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; curl -i --header "Content-Type: application/json" --header "X-ClientCode: shashi_train" --request POST --data "{\"Sponsor\":{\"SponsorId\":\"boeing\"}}" http://localhost:50167/service/1.0/sponsorlookup 
          restartPolicy: OnFailure
